version: "3"
services:
  app:
    container_name: task-manager-api
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"